#Requires -Version 7
#Requires -Modules ImportExcel, Toolbox.Remoting
#Requires -Modules Toolbox.PermissionMatrix, Toolbox.ActiveDirectory

<#
    .SYNOPSIS
        Creates/checks/fixes a folder structure based on permissions defined in
        an Excel file.

    .DESCRIPTION
        This script launches the script 'Sync permissions' to apply the
        permission matrix (Check, Fix, New).

    .PARAMETER ImportDir
        The path where the Excel files (matrixes) are located.

    .PARAMETER Archive
        When the 'Archive' switch is used the files will be moved to the folder
        'Archive' in the source directory.

    .PARAMETER DefaultsFile
        The Excel file that contains the worksheets 'Permissions', which
        contain the default permissions that need to be applied everywhere, and
        'MailTo', containing the e-mail addresses of users that need to receive
        the report on the results.

        This can be an absolute path to the file or a file name with extension
        that is located within the ImportDir.

    .PARAMETER Regex
        The Regex parameter is used to identify incorrect input in the Excel
        sheets. We only accept:
        L = List
        R = Read
        W = Write
        F = Full Control
        I = Ignore

    .PARAMETER DetailedLog
        When set to true, the script will be able to log more details for
        better troubleshooting. In case of ACL's that are incorrect, in normal
        circumstances only the FullName of the path is reported. When
        DetailedLog is enabled, the ACL's that are on the folder and the
        expected ACL are also reported.

        Keep in mind that when enabling DetailedLog, the script execution
        performance will drop. For this reason it is only advised to use this
        feature only in case of troubleshooting.

    .PARAMETER CherwellFolder
        The path to the folder where the csv files for Cherwell are saved. These
        files are used by Cherwell to create an interactive form containing the
        SamAccountName and other fields so end users can easily select the
        AD objects that are generated by a matrix file.

    .PARAMETER CherwellExcelOverviewFileName
        The log name of the Excel file containing the same data as the csv files
        exported to the Cherwell folder.

    .PARAMETER CherwellAdObjectsFileName
        The name of the csv file containing the AD object names generated by
        the combination of GroupName and SiteCode in the settings rows,
        combined with the headers in the permissions worksheet.

    .PARAMETER CherwellGroupManagersFileName
        The name of the csv file containing the group managers for all matrix
        files.

    .PARAMETER CherwellAccessListFileName
        The name of the csv file containing the access list for all matrix
        files.

    .PARAMETER CherwellExcelOverviewFileName
        The log name of the Excel file containing the same data as the csv files
        exported to the Cherwell folder.

    .PARAMETER MaxConcurrentComputers
        Maximum quantity of unique computer names that can be requested to
        perform jobs at the same time.

    .PARAMETER MaxConcurrentJobsPerRemoteComputer
        Maximum quantity of jobs to run at the same time on a single remote
        computer.

    .PARAMETER MaxConcurrentFoldersPerMatrix
        Maximum quantity of folders to iterate at the same time within a
        single job running on a remote computer.

    .PARAMETER PSSessionConfiguration
        The version of PowerShell on the remote endpoint as returned by
        Get-PSSessionConfiguration.
#>

[CmdLetBinding()]
param (
    [Parameter(Mandatory)]
    [String]$ConfigurationJsonFile,
    [Parameter(Mandatory)]
    [String]$ScriptName,
    [Parameter(Mandatory)]
    [String]$ImportDir,
    [String]$DefaultsFile = "$ImportDir\Defaults.xlsx",
    [HashTable]$ScriptPath = @{
        TestRequirementsFile = "$PSScriptRoot\Test requirements.ps1"
        SetPermissionFile    = "$PSScriptRoot\Set permissions.ps1"
    },
    [String[]]$ExcludedSamAccountName = 'belsrvc',
    [Switch]$Archive,
    [Boolean]$DetailedLog = $true,
    [String]$CherwellFolder,
    [String]$CherwellAdObjectsFileName = 'AD object names.csv',
    [String]$CherwellFormDataFileName = 'Form data.csv',
    [String]$CherwellGroupManagersFileName = 'GroupManagers.csv',
    [String]$CherwellAccessListFileName = 'AccessList.csv',
    [String]$CherwellExcelOverviewFileName = 'Overview.xlsx',
    [int]$MaxConcurrentComputers = 10,
    [Int]$MaxConcurrentJobsPerRemoteComputer = 3,
    [Int]$MaxConcurrentFoldersPerMatrix = 3,
    [String]$PSSessionConfiguration = 'PowerShell.7',
    [String]$LogFolder = "$env:POWERSHELL_LOG_FOLDER\File or folder\Permission matrix set permissions\$ScriptName",
    [String[]]$ScriptAdmin = @(
        $env:POWERSHELL_SCRIPT_ADMIN,
        $env:POWERSHELL_SCRIPT_ADMIN_BACKUP
    )
)

begin {
    function ConvertTo-HtmlValueHC {
        if (-not $E.Value) {
            $null
        }
        elseif (($E.Value.Count -le 5) -and (-not ($E.Value -is [HashTable]))) {
            @"
        <ul>
            $(@($E.Value).ForEach({"<li>$_</li>"}))
        </ul>
"@
        }
        else {
            $fileName = "ID $($S.ID) - $($E.Type) - $($E.Name).txt".Split([IO.Path]::GetInvalidFileNameChars()) -join '_'

            $OutParams = @{
                LiteralPath = Join-Path -Path $I.File.LogFolder -ChildPath $fileName
                Encoding    = 'utf8'
                NoClobber   = $true
            }
            $E | ConvertTo-Json -Depth 100 | ForEach-Object {
                [System.Text.RegularExpressions.Regex]::Unescape($_)
            } | Out-File @OutParams
            @"
        <ul>
            <li><a href="$($OutParams.LiteralPath)">$("$($E.Value.Count) items")</a></li>
        </ul>
"@
        }
    }
    function Get-HTNLidTagProbTypeHC {
        [OutputType([String[]])]
        param (
            [Parameter(Mandatory)]
            [String]$Name
        )

        try {
            switch ($Name) {
                'FatalError' {
                    'probTypeError'
                    break
                }
                'Warning' {
                    'probTypeWarning'
                    break
                }
                'Information' {
                    'probTypeInfo'
                    break
                }
                default {
                    throw "Type '$_' is unknown"
                }
            }
        }
        catch {
            throw "Failed converting the HTML name '$Name' to a valid HTML ID tag: $_"
        }
    }

    try {
        $StartDate = Get-ScriptRuntimeHC -Start
        Import-EventLogParamsHC -Source $ScriptName
        Write-EventLog @EventStartParams

        Get-Job | Remove-Job -Force

        #region Test path exists
        $scriptPathItem = @{}

        $ScriptPath.GetEnumerator().ForEach(
            {
                try {
                    $key = $_.Key
                    $value = $_.Value

                    $params = @{
                        Path        = $value
                        ErrorAction = 'Stop'
                    }
                    $scriptPathItem[$key] = (Get-Item @params).FullName
                }
                catch {
                    throw "ScriptPath.$key '$value' not found"
                }
            }
        )
        #endregion

        #region Test Cherwell parameters
        if ($CherwellFolder) {
            if (-not
                (Test-Path -LiteralPath $CherwellFolder -PathType Container)
            ) {
                throw "Cherwell folder '$CherwellFolder' not found"
            }

            @(
                'CherwellAdObjectsFileName',
                'CherwellFormDataFileName',
                'CherwellAccessListFileName',
                'CherwellGroupManagersFileName',
                'CherwellExcelOverviewFileName'
            ).Where( {
                    -not (Get-Variable -Name $_).Value
                }).foreach( {
                    throw "Parameter '$_' is mandatory when the parameter CherwellFolder is used."
                })
        }
        #endregion

        #region Create log folder
        try {
            $LogFolder = (New-Item -ItemType 'Directory' -Path $LogFolder -Force -EA Stop).FullName
        }
        catch {
            throw "Failed to create log folder '$LogFolder': $_"
        }
        #endregion

        #region Map share with Excel files
        if (-not (Test-Path -LiteralPath ImportDir:)) {
            $RetryCount = 0; $Completed = $false
            while (-not $Completed) {
                try {
                    $null = New-PSDrive -Name ImportDir -PSProvider FileSystem -Root $ImportDir -EA Stop
                    $Completed = $true
                }
                catch {
                    if ($RetryCount -ge '240') {
                        throw "Drive mapping failed for '$ImportDir': $_"
                    }
                    else {
                        Start-Sleep -Seconds 30
                        $RetryCount++
                        $Error.Clear()
                    }
                }
            }
        }

        $ImportDir = Get-Item $ImportDir -EA Stop
        #endregion

        #region Default settings file
        try {
            #region Get the defaults
            $DefaultsItem = Get-Item -LiteralPath $DefaultsFile -EA Stop

            try {
                $DefaultsImport = Import-Excel -Path $DefaultsItem -Sheet 'Settings' -DataOnly -ErrorAction 'Stop'
            }
            catch {
                throw "worksheet 'Settings' not found*"
            }
            #endregion

            #region Verify mandatory column headers
            $propDefault = $DefaultsImport.ForEach( {
                    $_.PSObject.Properties.Name
                })

            @('MailTo', 'ADObjectName', 'Permission').Where( { $propDefault -notcontains $_ }).ForEach( {
                    throw "Column header '$_' not found. The column headers 'MailTo', 'ADObjectName' and 'Permission' are mandatory."
                })
            #endregion

            $DefaultAcl = Get-DefaultAclHC -Sheet $DefaultsImport

            #region Get MailTo
            $MailTo = $DefaultsImport.ForEach( {
                    $_.PSObject.Properties.Where( { ($_.Name -eq 'MailTo') -and ($_.Value) }).Foreach( {
                            $_.Value.ToString().Trim()
                        })
                })

            if (-not $MailTo) {
                throw "No mail addresses found under column header 'MailTo'"
            }
            #endregion
        }
        catch {
            throw "Defaults file '$DefaultsFile' worksheet 'Settings': $_"
        }
        #endregion

        if ($Archive) {
            try {
                $archivePath = Join-Path -Path $ImportDir -ChildPath 'Archive'

                $ArchiveItem = (New-Item -ItemType 'Directory' -Path $archivePath -Force -EA Stop).FullName
            }
            catch {
                throw "Failed to create archive folder '$archivePath': $_"
            }
        }
    }
    catch {
        Write-Warning $_
        Send-MailHC -To $ScriptAdmin -Subject FAILURE -Priority High -Message $_ -Header $ScriptName
        Write-EventLog @EventErrorParams -Message "FAILURE Incorrect input:`n`n- $_"
        Write-EventLog @EventEndParams; exit 1
    }
}

process {
    try {
        $ID = 0

        $getParams = @{
            Path        = 'ImportDir:\*'
            Include     = '*.xlsx'
            File        = $true
            ErrorAction = 'Stop'
        }

        [Array]$importedMatrix = foreach (
            $matrixFile in
            @(Get-ChildItem @getParams).Where(
                { $_.FullName -ne $DefaultsItem.FullName })
        ) {
            try {
                Write-Verbose "Matrix file '$matrixFile'"

                $Obj = [PSCustomObject]@{
                    File        = @{
                        Item         = $matrixFile
                        SaveFullName = $matrixFile.FullName
                        ExcelInfo    = $null
                        LogFolder    = $null
                        Check        = @()
                    }
                    Settings    = @()
                    Permissions = @{
                        Import = @()
                        Check  = @()
                    }
                    FormData    = @{
                        Import = $null
                        Check  = @()
                    }
                }

                #region Create log folder
                try {
                    $logFolderPath = Join-Path -Path $LogFolder -ChildPath (
                        '{0:00}-{1:00}-{2:00} {3:00}{4:00} ({5}) - {6}' -f $StartDate.Year, $StartDate.Month,
                        $StartDate.Day, $StartDate.Hour, $StartDate.Minute, $StartDate.DayOfWeek, $matrixFile.BaseName)

                    $Obj.File.LogFolder = (New-Item -ItemType 'Directory' -Path $logFolderPath -Force -EA Stop).FullName
                }
                catch {
                    throw "Failed to create log folder '$logFolderPath': $_"
                }

                $BeginEvent = "$($matrixFile.Name)`n`nExcel file details:`n"
                #endregion

                #region Copy file to log folder
                try {
                    $copyParams = @{
                        LiteralPath = $matrixFile.FullName
                        Destination = $Obj.File.LogFolder
                        PassThru    = $true
                        ErrorAction = 'Stop'
                    }

                    Write-Verbose "Copy file '$($copyParams.LiteralPath)' to '$($copyParams.Destination)'"

                    $Obj.File.SaveFullName = (Copy-Item @copyParams).FullName
                }
                catch {
                    throw "Failed to copy file '$($copyParams.LiteralPath)' to '$($copyParams.Destination)': $_"
                }
                #endregion

                #region Get Excel file details
                $Obj.File.ExcelInfo = Get-ExcelWorkbookInfo -Path $matrixFile.FullName -ErrorAction 'Stop'

                $M = ($BeginEvent +
                    "- Name:`t`t`t" + $matrixFile.Name + "`n" +
                    "- DirectoryName:`t`t" + $matrixFile.DirectoryName + "`n" +
                    "- LastModifiedBy:`t`t" + $Obj.File.ExcelInfo.LastModifiedBy + "`n" +
                    "- LastModifiedDate:`t" + $Obj.File.ExcelInfo.Modified.ToString('dd/MM/yyyy HH:mm:ss'))
                Write-Verbose $M
                Write-EventLog @EventVerboseParams -Message $M
                #endregion

                #region Import sheets Settings, Permissions, FormData
                try {
                    $ImportParams = @{
                        Path        = $matrixFile.FullName
                        DataOnly    = $true
                        ErrorAction = 'Stop'
                    }
                    #region Import sheet Settings
                    $Settings = @(
                        Import-Excel @ImportParams -Sheet 'Settings'
                    ).Where(
                        { $_.Status -eq 'Enabled' }
                    )
                    $M = "$BeginEvent - Worksheet 'Settings' imported with 'Status' set to 'Enabled': $Settings"
                    Write-EventLog @EventVerboseParams -Message $M
                    Write-Verbose $M
                    #endregion

                    if ($Settings) {
                        foreach ($S in $Settings) {
                            $ID++

                            $Obj.Settings += [PSCustomObject]@{
                                ID        = $ID
                                Import    = Format-SettingStringsHC -Settings $S
                                Check     = @()
                                Matrix    = @()
                                AdObjects = @{}
                                JobTime   = @{}
                            }
                        }

                        #region Import sheet Permissions
                        $Obj.Permissions.Import = @(
                            Import-Excel @ImportParams -Sheet 'Permissions' -NoHeader |
                            Format-PermissionsStringsHC
                        )

                        $M = "$BeginEvent - Worksheet 'Permissions' imported"
                        Write-EventLog @EventVerboseParams -Message $M
                        Write-Verbose $M
                        #endregion

                        #region Import sheet FormData
                        if ($CherwellFolder) {
                            try {
                                $formData = Import-Excel @ImportParams -Sheet 'FormData' -ErrorVariable importFail

                                $M = "$BeginEvent - Worksheet 'FormData' imported"
                                Write-EventLog @EventVerboseParams -Message $M
                                Write-Verbose $M

                                $Obj.FormData.Check += Test-FormDataHC $formData

                                if (-not $Obj.FormData.Check) {
                                    $Obj.FormData.Import = $formData
                                }
                            }
                            catch {
                                $Obj.File.Check += [PSCustomObject]@{
                                    Type        = 'FatalError'
                                    Name        = "Worksheet 'FormData' not found"
                                    Description = "When the argument 'CherwellFolder' is used the Excel file needs to have a worksheet 'FormData'."
                                    Value       = @($_)
                                }
                                # remove multiple errors from Import-Excel
                                $importFail | ForEach-Object {
                                    $Error.Remove($_)
                                }
                            }
                        }
                        #endregion
                    }
                    else {
                        $Obj.File.Check += [PSCustomObject]@{
                            Type        = 'Warning'
                            Name        = 'Matrix disabled'
                            Description = 'Every Excel file needs at least one enabled matrix.'
                            Value       = "The worksheet 'Settings' does not contain a row with 'Status' set to 'Enabled'."
                        }
                        Write-EventLog @EventVerboseParams -Message "$BeginEvent - No lines found with status 'Enabled' in the worksheet 'Settings'"
                    }
                }
                catch {
                    $errorMessage = switch -Wildcard ($_) {
                        "*Worksheet 'Settings' not found*" {
                            "Worksheet 'Settings' not found"; break
                        }
                        "*worksheet 'Settings': No column headers found on top row '1'*" {
                            "Worksheet 'Settings' is empty"; break
                        }
                        "*Worksheet 'Permissions' not found*" {
                            "Worksheet 'Permissions' not found"; break
                        }
                        "*worksheet 'Permissions': No column headers found on top row '1'*" {
                            "Worksheet 'Permissions' is empty"; break
                        }
                        default {
                            throw "Failed importing the Excel file '$($matrixFile.FullName)': $_"
                        }
                    }
                    $Obj.File.Check += [PSCustomObject]@{
                        Type        = 'FatalError'
                        Name        = 'Excel file incorrect'
                        Description = "The worksheets 'Settings' and 'Permissions' are mandatory."
                        Value       = $errorMessage
                    }

                    try { $Error.RemoveRange(0, 2) }
                    catch { throw 'Import-Excel throws 2 errors normally' }
                }
                #endregion

                if ($Archive) {
                    try {
                        Move-Item -LiteralPath $matrixFile -Destination $ArchiveItem -Force -EA Stop

                        $M = "$BeginEvent - Moved file to archive folder:`n$($ArchiveItem.FullName)"
                        Write-EventLog @EventVerboseParams -Message $M
                        Write-Verbose $M
                    }
                    catch {
                        $Obj.File.Check += [PSCustomObject]@{
                            Type        = 'Warning'
                            Name        = 'Archiving failed'
                            Description = "When the '-Archive' switch is used the file is moved to the archive folder.In case a file is still in use, the move operation might fail."
                            Value       = @($_)
                        }

                        $Error.RemoveAt(0)
                    }
                }

                $Obj
            }
            catch {
                Write-Warning $_
                Send-MailHC -To $ScriptAdmin -Subject 'FAILURE' -Priority 'High' -Message $_ -Header $ScriptName
                Write-EventLog @EventErrorParams -Message "FAILURE:`n`n- $_"
                Write-EventLog @EventEndParams; exit 1
            }
        }

        if ($importedMatrix) {
            #region Build FormData for CherwellFolder
            foreach ($I in ($importedMatrix.Where( { $_.FormData.Import }))) {
                try {
                    $property = @{}

                    #region Convert MatrixResponsible to UserPrincipalName
                    $params = @{
                        Name                  = $I.FormData.Import.MatrixResponsible.Split(',').Trim()
                        ExcludeSamAccountName = $ExcludedSamAccountName
                    }
                    $result = Get-AdUserPrincipalNameHC @params

                    $property.MatrixResponsible = $result.userPrincipalName -join ','

                    if ($result.notFound) {
                        $I.FormData.Check += [PSCustomObject]@{
                            Type        = 'Warning'
                            Name        = 'AD object not found'
                            Description = "The email address or SamAccountName is not found in the active directory. Multiple entries are supported with the comma ',' separator."
                            Value       = $result.notFound
                        }
                    }
                    #endregion

                    #region Add MatrixFilePath and MatrixFileName
                    $property.MatrixFilePath = if ($Archive) {
                        Join-Path $ArchiveItem $I.File.Item.Name
                    }
                    else {
                        $I.File.Item.FullName
                    }

                    $property.MatrixFileName = $I.File.Item.BaseName
                    #endregion

                    $I.FormData.Import | Add-Member -NotePropertyMembers $property -Force
                }
                catch {
                    $I.FormData.Check += [PSCustomObject]@{
                        Type        = 'FatalError'
                        Name        = 'Failed adding property'
                        Description = "The worksheet 'FormData' could not be updated correctly."
                        Value       = @($_)
                    }
                }
            }
            #endregion

            #region Build the matrix and check for incorrect input
            $M = 'Build the matrix and check for incorrect input'
            Write-Verbose $M; Write-EventLog @EventVerboseParams -Message $M

            foreach (
                $I in
                $importedMatrix.Where(
                    {
                        ($_.File.Check.Type -notcontains 'FatalError' ) -and
                        ($_.Settings)
                    }
                )
            ) {
                try {
                    Write-Verbose 'Test matrix permissions'

                    $I.Permissions.Check += Test-MatrixPermissionsHC -Permissions $I.Permissions.Import

                    if ($I.Permissions.Check.Type -notcontains 'FatalError') {
                        foreach ($S in $I.Settings) {
                            $S.Check += Test-MatrixSettingHC -Setting $S.Import

                            #region Create AD object names
                            Write-Verbose 'Create AD object names'

                            $params = @{
                                Begin         = $S.Import.GroupName
                                Middle        = $S.Import.SiteCode
                                ColumnHeaders = $I.Permissions.Import |
                                Select-Object -First 3
                            }
                            $adObjects = ConvertTo-MatrixADNamesHC @params

                            Write-Verbose 'Test AD objects'

                            $S.Check += Test-AdObjectsHC $adObjects
                            #endregion

                            #region Create matrix for each settings line
                            if ($S.Check.Type -notcontains 'FatalError') {
                                Write-Verbose 'Create matrix for each settings line'

                                $S.AdObjects = $adObjects

                                $params = @{
                                    NonHeaderRows = $I.Permissions.Import |
                                    Select-Object -Skip 3
                                    ADObjects     = $adObjects
                                }
                                $S.Matrix += ConvertTo-MatrixAclHC @params
                            }
                            #endregion
                        }
                    }
                }
                catch {
                    $I.File.Check += [PSCustomObject]@{
                        Type        = 'FatalError'
                        Name        = 'Unknown error'
                        Description = 'While checking the input and generating the matrix an error was reported.'
                        Value       = $_
                    }
                    $Error.RemoveAt(0)
                }
            }
            #endregion

            #region Duplicate ComputerName/Path combination
            Write-EventLog @EventVerboseParams -Message 'Check duplicate ComputerName/Path combination'

            (
                @($importedMatrix.Settings | Group-Object @{
                        Expression = {
                            $_.Import.ComputerName + ' - ' + $_.Import.Path }
                    }
                ).Where( { $_.Count -ge 2 })
            ).Group.Foreach(
                {
                    $_.Check += [PSCustomObject]@{
                        Type        = 'FatalError'
                        Name        = 'Duplicate ComputerName/Path combination'
                        Description = "Every 'ComputerName' combined with a 'Path' needs to be unique over all the 'Settings' worksheets found in all the active matrix files."
                        Value       = @{
                            $_.Import.ComputerName = $_.Import.Path
                        }
                    }
                }
            )
            #endregion

            #region Check expanded matrix and get AD object details
            $M = 'Check expanded matrix'
            Write-Verbose $M; Write-EventLog @EventVerboseParams -Message $M

            $AdObjects = $importedMatrix.Settings.Matrix.ACL.Keys

            if ($AdObjects.count -ne 0) {
                Write-Verbose 'Get AD object details'
                $params = @{
                    ADObjectName = $AdObjects | Sort-Object -Unique
                    Type         = 'SamAccountName'
                }
                $ADObjectDetails = @(Get-ADObjectDetailHC @params)

                @($importedMatrix.Settings).Where( { $_.Matrix }).Foreach(
                    {
                        Write-Verbose "Test expanded matrix for Settings row ComputerName '$($_.Import.ComputerName)' Path '$($_.Import.Path)' SiteName '$($_.Import.SiteName)' SiteCode '$($_.Import.SiteCode)' GroupName '$($_.Import.GroupName)'"

                        $params = @{
                            Matrix                 = $_.Matrix
                            ADObject               = $ADObjectDetails
                            DefaultAcl             = $DefaultAcl
                            ExcludedSamAccountName = $ExcludedSamAccountName
                        }
                        $_.Check += Test-ExpandedMatrixHC @params
                    }
                )
            }
            #endregion

            #region Get AD object details for group managers
            if (
                $groupManagers = $ADObjectDetails.ADObject.ManagedBy |
                Sort-Object -Unique
            ) {
                $M = "Retrieve AD object details for $($groupManagers.Count) group managers"
                Write-Verbose $M; Write-EventLog @EventVerboseParams -Message $M

                $params = @{
                    ADObjectName = $groupManagers
                    Type         = 'DistinguishedName'
                }
                $groupManagersAdDetails = Get-ADObjectDetailHC @params
            }
            #endregion

            #region Remove group members that are in the ExcludedSamAccountName
            if ($ExcludedSamAccountName) {
                foreach ($adObject in $ADObjectDetails) {
                    $adObject.adGroupMember = $adObject.adGroupMember |
                    Where-Object {
                        $ExcludedSamAccountName -notcontains $_.SamAccountName
                    }
                }
                foreach ($adObject in $groupManagersAdDetails) {
                    $adObject.adGroupMember = $adObject.adGroupMember |
                    Where-Object {
                        $ExcludedSamAccountName -notcontains $_.SamAccountName
                    }
                }
            }
            #endregion

            #region Test server requirements
            if (
                $executableMatrix = @(
                    Get-ExecutableMatrixHC -From $importedMatrix)
            ) {
                $M = 'Check server requirements'
                Write-Verbose $M; Write-EventLog @EventVerboseParams -Message $M

                $scriptBlock = {
                    try {
                        #region Declare variables for parallel execution
                        if (-not $MaxConcurrentComputers) {
                            $scriptPathItem = $using:scriptPathItem
                            $PSSessionConfiguration = $using:PSSessionConfiguration
                        }
                        #endregion

                        $matrix = $_.Group
                        $computerName = $_.Name

                        $params = @{
                            FilePath          = $scriptPathItem.TestRequirementsFile
                            ArgumentList      = $matrix.Import.Path, $true
                            ConfigurationName = $PSSessionConfiguration
                            ComputerName      = $computerName
                            ErrorAction       = 'Stop'
                        }
                        if ($result = Invoke-Command @params) {
                            $matrix | ForEach-Object { $_.Check += $result }
                        }
                    }
                    catch {
                        $problem = [PSCustomObject]@{
                            Type        = 'FatalError'
                            Name        = 'Computer requirements'
                            Value       = $_
                            Description = "Failed checking the computer for the minimal requirements with the 'Test requirements' script."
                        }
                        $Error.RemoveAt(0)
                        $matrix | ForEach-Object { $_.Check += $problem }
                    }
                }

                #region Run code serial or parallel
                $foreachParams = if ($MaxConcurrentComputers -eq 1) {
                    @{
                        Process = $scriptBlock
                    }
                }
                else {
                    @{
                        Parallel      = $scriptBlock
                        ThrottleLimit = $MaxConcurrentComputers
                    }
                }
                #endregion

                $executableMatrix |
                Group-Object -Property { $_.Import.ComputerName } |
                ForEach-Object @foreachParams
            }
            #endregion

            #region Set permissions
            if (
                $executableMatrix = @(
                    Get-ExecutableMatrixHC -From $importedMatrix)
            ) {
                $M = "Start 'Set permissions' script for '$($executableMatrix.Count)' matrix"
                Write-Verbose $M; Write-EventLog @EventVerboseParams -Message $M

                #region Add default permissions
                <#
                    In case of conflict the acl in the matrix will win
                    over the acl in the DefaultsFile.
                #>
                if ($DefaultAcl.Count -ne 0) {
                    foreach (
                        $acl in
                        @($executableMatrix.Matrix.ACL).Where(
                            { $_.Count -ne 0 }
                        )
                    ) {
                        $DefaultAcl.GetEnumerator().Where(
                            { -not $acl.ContainsKey($_.Key) }
                        ).Foreach(
                            { $acl.Add($_.Key, $_.Value) }
                        )
                    }
                }
                #endregion

                $matrixes = $null

                $outerScriptBlock = {
                    # $VerbosePreference = 'Continue'

                    $matrixes = $_.Group

                    #region Declare variables for parallel execution
                    if (-not $MaxConcurrentComputers) {
                        $MaxConcurrentFoldersPerMatrix = $using:MaxConcurrentFoldersPerMatrix
                        $scriptPathItem = $using:scriptPathItem
                        $PSSessionConfiguration = $using:PSSessionConfiguration
                        $DetailedLog = $using:DetailedLog
                    }
                    #endregion

                    $innerScriptBlock = {
                        try {
                            # $VerbosePreference = 'Continue'

                            $matrix = $_

                            #region Declare variables for parallel execution
                            if (-not $MaxConcurrentJobsPerRemoteComputer) {
                                $MaxConcurrentFoldersPerMatrix = $using:MaxConcurrentFoldersPerMatrix
                                $scriptPathItem = $using:scriptPathItem
                                $PSSessionConfiguration = $using:PSSessionConfiguration
                                $DetailedLog = $using:DetailedLog
                            }
                            #endregion

                            $matrix.JobTime.Start = Get-Date

                            $params = @{
                                FilePath          = $scriptPathItem.SetPermissionFile
                                ArgumentList      = $matrix.Import.Path, $matrix.Import.Action, $matrix.Matrix, $MaxConcurrentFoldersPerMatrix, $DetailedLog
                                ConfigurationName = $PSSessionConfiguration
                                ComputerName      = $matrix.Import.ComputerName
                                ErrorAction       = 'Stop'
                            }
                            if ($result = Invoke-Command @params) {
                                $matrix.Check += $result
                            }
                        }
                        catch {
                            $problem = [PSCustomObject]@{
                                Type        = 'FatalError'
                                Name        = 'Set permissions'
                                Value       = $_
                                Description = "Failed applying action '$($matrix.Import.Action)' with the 'Set permissions' script."
                            }
                            $Error.RemoveAt(0)
                            $matrix.Check += $problem
                        }
                        finally {
                            $matrix.JobTime.End = Get-Date
                            $matrix.JobTime.Duration = New-TimeSpan -Start $matrix.JobTime.Start -End $matrix.JobTime.End
                        }
                    }

                    $innerForeachParams = @{
                        Process = $innerScriptBlock
                    }

                    if (-not $MaxConcurrentJobsPerRemoteComputer) {
                        $innerForeachParams = @{
                            Parallel      = $innerScriptBlock
                            ThrottleLimit = $using:MaxConcurrentJobsPerRemoteComputer
                        }
                    }

                    $matrixes | ForEach-Object @innerForeachParams
                }

                $foreachParams = @{
                    Process = $outerScriptBlock
                }

                if ($MaxConcurrentComputers -gt 1) {
                    $foreachParams = @{
                        Parallel      = $outerScriptBlock
                        ThrottleLimit = $MaxConcurrentComputers
                    }
                }

                $executableMatrix |
                Group-Object -Property { $_.Import.ComputerName } |
                ForEach-Object @foreachParams -Verbose
            }
            #endregion
        }
    }
    catch {
        Write-Warning $_
        Get-Job | Remove-Job -Force -EA Ignore
        Send-MailHC -To $ScriptAdmin -Subject FAILURE -Priority High -Message $_ -Header $ScriptName
        Write-EventLog @EventErrorParams -Message "FAILURE:`n`n- $_"
        Write-EventLog @EventEndParams; exit 1
    }
}

end {
    try {
        $matrixLogFile = Join-Path -Path $LogFolder -ChildPath (
            '{0:00}-{1:00}-{2:00} {3:00}{4:00} ({5})' -f
            $StartDate.Year, $StartDate.Month, $StartDate.Day,
            $StartDate.Hour, $StartDate.Minute, $StartDate.DayOfWeek
        )

        if ($importedMatrix) {
            $groupManagersSheet = @()
            $accessListSheet = @()

            #region Export to matrix Excel log file
            foreach ($I in $importedMatrix) {
                #region Get unique SamAccountNames for all matrix in Settings
                $matrixSamAccountNames = $i.Settings.AdObjects.Values.SamAccountName |
                Select-Object -Property @{
                    Name       = 'name'
                    Expression = { "$($_)".Trim() }
                } -Unique |
                Select-Object -ExpandProperty name

                $M = "Matrix '$($i.File.Item.Name)' has '$($matrixSamAccountNames.count)' unique SamAccountNames"
                Write-Verbose $M; Write-EventLog @EventVerboseParams -Message $M
                #endregion

                #region Create Excel worksheet 'AccessList'
                $accessListToExport = foreach ($S in $matrixSamAccountNames) {
                    $adData = $ADObjectDetails |
                    Where-Object { $S -eq $_.samAccountName }

                    if (-not $adData.adObject) {
                        $M = "Matrix '$($i.File.Item.Name)' SamAccountName '$s' not found in AD"
                        Write-Warning $M; Write-EventLog @EventWarnParams -Message $M
                    }
                    elseif (-not $adData.adGroupMember) {
                        $adData | Select-Object -Property SamAccountName,
                        @{Name = 'Name'; Expression = { $_.adObject.Name } },
                        @{Name = 'Type'; Expression = { $_.adObject.ObjectClass } },
                        MemberName, MemberSamAccountName
                    }
                    else {
                        $adData.adGroupMember | Select-Object -Property @{
                            Name       = 'SamAccountName'
                            Expression = { $S }
                        },
                        @{Name = 'Name'; Expression = { $adData.adObject.Name } },
                        @{Name = 'Type'; Expression = { $adData.adObject.ObjectClass } },
                        @{Name = 'MemberName'; Expression = { $_.Name } },
                        @{Name = 'MemberSamAccountName'; Expression = { $_.SamAccountName } }
                    }
                }
                #endregion

                #region Create Excel worksheet 'GroupManagers'
                $groupManagersToExport = foreach ($S in $matrixSamAccountNames) {
                    $adData = (
                        $ADObjectDetails | Where-Object {
                            ($S -eq $_.samAccountName) -and
                            ($_.adObject.ObjectClass -eq 'group')
                        }
                    )
                    if ($adData) {
                        $groupManager = $groupManagersAdDetails | Where-Object {
                            $_.DistinguishedName -eq $adData.adObject.ManagedBy
                        }

                        if (-not $groupManager) {
                            [PSCustomObject]@{
                                GroupName         = $adData.adObject.Name
                                ManagerName       = $null
                                ManagerType       = $null
                                ManagerMemberName = $null
                            }
                        }
                        elseif (-not $groupManager.adGroupMember) {
                            [PSCustomObject]@{
                                GroupName         = $adData.adObject.Name
                                ManagerName       = $groupManager.adObject.Name
                                ManagerType       = $groupManager.adObject.ObjectClass
                                ManagerMemberName = $null
                            }
                        }
                        else {
                            foreach ($user in $groupManager.adGroupMember) {
                                [PSCustomObject]@{
                                    GroupName         = $adData.adObject.Name
                                    ManagerName       = $groupManager.adObject.Name
                                    ManagerType       = $groupManager.adObject.ObjectClass
                                    ManagerMemberName = $user.Name
                                }
                            }
                        }
                    }
                }
                #endregion

                if ($accessListToExport) {
                    #region Export to Excel worksheet 'AccessList'
                    $excelParams = @{
                        Path               = $I.File.SaveFullName
                        AutoSize           = $true
                        WorksheetName      = 'AccessList'
                        TableName          = 'AccessList'
                        FreezeTopRow       = $true
                        NoNumberConversion = '*'
                        ClearSheet         = $true
                    }

                    $M = "Export $($accessListToExport.Count) AD objects to Excel file '$($excelParams.Path)' worksheet '$($excelParams.WorksheetName)'"
                    Write-Verbose $M; Write-EventLog @EventOutParams -Message $M

                    $accessListToExport | Export-Excel @excelParams
                    #endregion

                    #region Create 'AccessList' to export for Cherwell
                    if ($CherwellFolder) {
                        $accessListSheet += $accessListToExport |
                        Select-Object @{
                            Name       = 'MatrixFileName'
                            Expression = { $I.File.Item.BaseName }
                        }, *
                    }
                    #endregion

                    if ($groupManagersToExport) {
                        #region Export to Excel worksheet 'GroupManagers'
                        $excelParams.WorksheetName = $excelParams.TableName = 'GroupManagers'

                        $M = "Export $($groupManagersToExport.Count) AD objects to Excel file '$($excelParams.Path)' worksheet '$($excelParams.WorksheetName)'"
                        Write-Verbose $M; Write-EventLog @EventOutParams -Message $M

                        $groupManagersToExport | Export-Excel @excelParams
                        #endregion

                        #region Create 'GroupManagers' to export for Cherwell
                        if ($CherwellFolder) {
                            $groupManagersSheet += $groupManagersToExport |
                            Select-Object @{
                                Name       = 'MatrixFileName'
                                Expression = { $I.File.Item.BaseName }
                            }, *
                        }
                        #endregion
                    }
                }
            }
            #endregion

            #region Export Cherwell FormData and AD Objects
            $formDataSheet = @()
            $adObjectNamesSheet = @()

            if (
                $CherwellFolder -and
                ($importedMatrix.FormData.Check.Type -notcontains 'FatalError')
            ) {
                #region Create AD Object names and FormData to export
                foreach ($I in $importedMatrix) {
                    $adObjects = foreach (
                        $S in
                        $I.Settings.Where( { $_.AdObjects.Count -ne 0 })
                    ) {
                        foreach ($A in ($S.AdObjects.GetEnumerator())) {
                            [PSCustomObject]@{
                                MatrixFileName	= $I.File.Item.BaseName
                                SamAccountName = $A.Value.SamAccountName
                                GroupName      = $A.Value.Converted.Begin
                                SiteCode       = $A.Value.Converted.Middle
                                Name           = $A.Value.Converted.End
                            }
                        }
                    }

                    if ($adObjects) {
                        $formDataSheet += $I.FormData.Import

                        $adObjectNamesSheet += $adObjects |
                        Group-Object SamAccountName |
                        ForEach-Object { $_.Group[0] }
                    }
                }
                #endregion

                #region Remove old exported files
                $ExportParams = @{
                    Path         = "$matrixLogFile - Cherwell - $CherwellExcelOverviewFileName"
                    AutoSize     = $true
                    FreezeTopRow = $true
                }
                $ExportParams.Path | Remove-Item -EA Ignore

                $exportCsvAdParams = @{
                    literalPath       = Join-Path $CherwellFolder $CherwellAdObjectsFileName
                    Encoding          = 'utf8'
                    NoTypeInformation = $true
                }
                $exportCsvAdParams.literalPath | Remove-Item -EA Ignore

                $exportCsvFormParams = @{
                    literalPath       = Join-Path $CherwellFolder $CherwellFormDataFileName
                    Encoding          = 'utf8'
                    NoTypeInformation = $true
                }
                $exportCsvFormParams.literalPath | Remove-Item -EA Ignore

                $exportCsvGroupManagersParams = @{
                    literalPath       = Join-Path $CherwellFolder $CherwellGroupManagersFileName
                    Encoding          = 'utf8'
                    NoTypeInformation = $true
                }
                $exportCsvGroupManagersParams.literalPath |
                Remove-Item -EA Ignore

                $exportCsvAccessListParams = @{
                    literalPath       = Join-Path $CherwellFolder $CherwellAccessListFileName
                    Encoding          = 'utf8'
                    NoTypeInformation = $true
                }
                $exportCsvAccessListParams.literalPath | Remove-Item -EA Ignore
                #endregion

                if ($AdObjectNamesSheet) {
                    #region Export AD object names to an Excel file
                    Write-EventLog @EventOutParams -Message "Export $($AdObjectNamesSheet.Count) AD object names to '$($ExportParams.Path)'"

                    $AdObjectNamesSheet |
                    Export-Excel @ExportParams -WorksheetName 'AdObjectNames' -TableName 'AdObjectNames'
                    #endregion

                    #region Export AD object names to a csv file
                    Write-EventLog @EventOutParams -Message "Export AD object names to '$($exportCsvAdParams.literalPath)'"

                    $adObjectNamesSheet | Export-Csv @exportCsvAdParams
                    #endregion

                    #region Copy csv file to log folder
                    $copyParams = @{
                        LiteralPath = $exportCsvAdParams.literalPath
                        Destination = "$matrixLogFile - Cherwell - $CherwellAdObjectsFileName"
                    }
                    Copy-Item @copyParams
                    #endregion
                }

                if ($groupManagersSheet) {
                    #region Export group managers to an Excel file
                    Write-EventLog @EventOutParams -Message "Export $($groupManagersSheet.Count) group managers to '$($ExportParams.Path)'"

                    $groupManagersSheet |
                    Export-Excel @ExportParams -WorksheetName 'GroupManagers' -TableName 'GroupManagers'
                    #endregion

                    #region Export group managers to a csv file
                    Write-EventLog @EventOutParams -Message "Export group managers to '$($exportCsvGroupManagersParams.literalPath)'"

                    $groupManagersSheet |
                    Export-Csv @exportCsvGroupManagersParams
                    #endregion

                    #region Copy csv file to log folder
                    $copyParams = @{
                        LiteralPath = $exportCsvGroupManagersParams.literalPath
                        Destination = "$matrixLogFile - Cherwell - $CherwellGroupManagersFileName"
                    }
                    Copy-Item @copyParams
                    #endregion
                }

                if ($accessListSheet) {
                    #region Export access list to an Excel file
                    Write-EventLog @EventOutParams -Message "Export $($accessListSheet.Count) access list to '$($ExportParams.Path)'"

                    $accessListSheet |
                    Export-Excel @ExportParams -WorksheetName 'AccessList' -TableName 'AccessList'
                    #endregion

                    #region Export access list to a csv file
                    Write-EventLog @EventOutParams -Message "Export access list to '$($exportCsvAccessListParams.literalPath)'"

                    $accessListSheet |
                    Export-Csv @exportCsvAccessListParams
                    #endregion

                    #region Copy csv file to log folder
                    $copyParams = @{
                        LiteralPath = $exportCsvAccessListParams.literalPath
                        Destination = "$matrixLogFile - Cherwell - $CherwellAccessListFileName"
                    }
                    Copy-Item @copyParams
                    #endregion
                }

                if ($formDataSheet) {
                    #region Export FormData to an Excel file
                    Write-EventLog @EventOutParams -Message "Export FormData to '$($ExportParams.Path)'"

                    $formDataSheet |
                    Export-Excel @ExportParams -WorksheetName 'FormData' -TableName 'FormData'
                    #endregion

                    #region Export FormData to a CSV file
                    Write-EventLog @EventOutParams -Message "Export FormData to '$($exportCsvFormParams.literalPath)'"

                    $formDataSheet | Export-Csv @exportCsvFormParams
                    #endregion

                    #region Export FormData to an HTML file
                    $htmlFileContent = @(
                        @'
<style>
  body {
    background-color: #f0f0f0;
    color: #004e2b;
    font-family: Arial, sans-serif;
    padding: 20px;
  }

  a {
    color: #004e2b;
    text-decoration: none;
  }
  a:hover {
    color: #00dd39;
    text-decoration: underline;
  }

  h1 {
    border-bottom: 2px solid #004e2b;
    padding-bottom: 10px;
    margin-bottom: 25px;
    color: #004e2b;
    text-transform: uppercase;
    font-size: 1.8em;
  }

  table {
    width: 100%;
    max-width: 1200px;
    margin: 20px 0;
    border-collapse: separate;
    border-spacing: 0;
    box-shadow: 0 6px 15px rgba(0, 0, 0, 0.2);
    background-color: #ffffff;
    border-radius: 8px;
    overflow: hidden;
    table-layout: auto;
    border: none;
  }

  table th {
    background-color: #004e2b;
    color: #ffffff;
    text-align: left;
    padding: 15px 20px;
    font-weight: bold;
    text-transform: uppercase;
    border: none;
    font-size: 0.9em;
  }

  table thead tr:first-child th:first-child {
    border-top-left-radius: 8px;
  }
  table thead tr:first-child th:last-child {
    border-top-right-radius: 8px;
  }

  table th:nth-child(3) {
    text-align: left;
    word-break: normal;
  }

  table td {
    text-align: center;
    padding: 10px 15px;
    border: none;
    border-bottom: 1px solid #e0e0e0;
    vertical-align: middle;
    color: #004e2b;
  }

  table tbody tr:last-child td {
    border-bottom: none;
  }

  table td:nth-child(3) {
    text-align: left;
    white-space: nowrap;
    word-break: normal;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  table td:nth-child(4) {
    text-align: left;
    white-space: nowrap;
    word-break: normal;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  table td:nth-child(5) {
    text-align: left;
    white-space: nowrap;
    word-break: normal;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  table tbody tr:nth-child(even) {
    background-color: #f8f8f8b7;
  }
  table tbody tr:nth-child(odd) {
    background-color: #ffffff;
  }

  table tbody tr:hover {
    background-color: #c2ebcf;
    color: #004e2b;
  }

  table tbody tr td a {
    display: block;
    width: 100%;
    height: 100%;
    color: #004e2b;
  }
  table td:last-child a {
    display: inline;
    color: #004e2b;
  }

  table tbody tr:hover td a {
    color: #004e2b;
  }
</style>
'@,
                        '<h1>Matrix files overview</h1>'
                    )

                    $htmlMatrixTableRows = '<tr>
                        <th>Category</th>
                        <th>Subcategory</th>
                        <th>Folder</th>
                        <th>Link to the matrix</th>
                        <th>Responsible</th>
                    </tr>
                    '

                    $htmlMatrixTableRows += $formDataSheet | 
                    Sort-Object -Property 'MatrixCategoryName', 'MatrixSubCategoryName', 'MatrixFolderDisplayName' | 
                    ForEach-Object {
                        $emailsMatrixResponsible = foreach (
                            $email in
                            $_.MatrixResponsible -split ','
                        ) {
                            "<a href=`"mailto:$email`">$email</a>"
                        }

                        "<tr>
                                <td>$($_.MatrixCategoryName)</td>
                                <td>$($_.MatrixSubCategoryName)</td>
                                <td><a href=`"$($_.MatrixFolderDisplayName)`">$($_.MatrixFolderDisplayName)</a></td>
                                <td><a href=`"$($_.MatrixFilePath)`">$($_.MatrixFileName)</a></td>
                                <td>$emailsMatrixResponsible</td>
                            </tr>"
                    }

                    $htmlFileContent += "<table>$htmlMatrixTableRows</table>"

                    $joinParams = @{
                        Path      = $CherwellFolder
                        ChildPath = $CherwellExcelOverviewFileName.Replace('.xlsx', '.html')
                    }
                    $htmlFilePath = Join-Path @joinParams

                    Write-EventLog @EventOutParams -Message "Export FormData to '$htmlFilePath'"

                    $htmlFileContent | Out-File -LiteralPath $htmlFilePath -Encoding utf8 -Force
                    #endregion

                    #region Copy csv file to log folder
                    $copyParams = @{
                        LiteralPath = $exportCsvFormParams.literalPath
                        Destination = "$matrixLogFile - Cherwell - $CherwellFormDataFileName"
                    }
                    Copy-Item @copyParams
                    #endregion
                }

                if ($adObjectNamesSheet -or $formDataSheet -or
                    $accessListSheet -or $groupManagersSheet) {
                    #region Copy Excel file from log folder to Cherwell folder
                    $copyParams = @{
                        LiteralPath = $ExportParams.Path
                        Destination = Join-Path $CherwellFolder $CherwellExcelOverviewFileName
                    }
                    Copy-Item @copyParams
                    #endregion
                }
            }
            #endregion

            #region HTML <style> for Mail and Settings
            Write-EventLog @EventVerboseParams -Message 'Format HTML'

            $htmlStyle = @'
<style>
    a {
        color: black;
        text-decoration: underline;
    }
    a:hover {
        color: blue;
    }

    #overviewTable {
        border-collapse: collapse;
        border: 1px solid Black;
        table-layout: fixed;
    }

    #overviewTable th {
        font-weight: normal;
        text-align: left;
    }
    #overviewTable td {
        text-align: center;
    }

    #matrixTable {
        border: 1px solid Black;
        /* padding-bottom: 60px; */
        /* border-spacing: 0.5em; */
        border-collapse: separate;
        border-spacing: 0px 0.6em;
        /* padding: 10px; */
        width: 600px;
    }

    #matrixTitle {
        border: none;
        background-color: lightgrey;
        text-align: center;
        padding: 6px;
    }

    #matrixHeader {
        font-weight: normal;
        letter-spacing: 5pt;
        font-style: italic;
    }

    #matrixFileInfo {
        font-weight: normal;
        font-size: 12px;
        font-style: italic;
        text-align: center;
    }

    #LegendTable {
        border-collapse: collapse;
        border: 1px solid Black;
        table-layout: fixed;
    }

    #LegendTable td {
        text-align: center;
    }

    #probTitle {
        font-weight: bold;
    }

    #probTypeWarning {
        background-color: orange;
    }
    #probTextWarning {
        color: orange;
        font-weight: bold;
    }

    #probTypeError {
        background-color: red;
    }
    #probTextError {
        color: red;
        font-weight: bold;
    }

    #probTypeInfo {
        background-color: lightgrey;
    }

    table tbody tr td a {
        display: block;
        width: 100%;
        height: 100%;
    }
</style>
'@
            #endregion

            #region HTML LegendTable for Mail and Settings
            $htmlLegend = @'
<table id="LegendTable">
    <tr>
        <td id="probTypeError" style="border: 1px solid Black;width: 150px;">Error</td>
        <td id="probTypeWarning" style="border: 1px solid Black;width: 150px;">Warning</td>
        <td id="probTypeInfo" style="border: 1px solid Black;width: 150px;">Information</td>
    </tr>
</table>
'@
            #endregion

            #region HTML Mail overview & Settings detail
            $htmlMatrixTables = foreach ($I in $importedMatrix) {
                #region HTML File
                $FileCheck = if ($I.File.Check) {
                    @'
                    <th id="matrixHeader" colspan="8">File</th>
'@

                    foreach ($F in $I.File.Check) {
                        $ProbType = Get-HTNLidTagProbTypeHC -Name $F.Type

                        $ProbValue = if ($F.Value) {
                            '<ul>'
                            @($F.Value).ForEach( { "<li>$_</li>" })
                            '</ul>'
                        }

                        @"
                        <tr>
                            <td id="$ProbType"></td>
                            <td colspan="7">
                                <p id="probTitle">$($F.Name)</p>
                                <p>$($F.Description)</p>
                                $ProbValue
                            </td>
                        </tr>
"@
                    }
                }
                #endregion

                #region HTML FormData
                $FormDataCheck = if ($I.FormData.Check) {
                    @'
                    <th id="matrixHeader" colspan="8">FormData</th>
'@

                    foreach ($F in $I.FormData.Check) {
                        $ProbType = Get-HTNLidTagProbTypeHC -Name $F.Type

                        $ProbValue = if ($F.Value) {
                            '<ul>'
                            @($F.Value).ForEach( { "<li>$_</li>" })
                            '</ul>'
                        }

                        @"
                        <tr>
                            <td id="$ProbType"></td>
                            <td colspan="7">
                                <p id="probTitle">$($F.Name)</p>
                                <p>$($F.Description)</p>
                                $ProbValue
                            </td>
                        </tr>
"@
                    }
                }
                #endregion

                #region HTML Permissions
                $PermissionsCheck = if ($I.Permissions.Check) {
                    @'
                    <th id="matrixHeader" colspan="8">Permissions</th>
'@

                    foreach ($F in $I.Permissions.Check) {
                        $ProbType = Get-HTNLidTagProbTypeHC -Name $F.Type

                        $ProbValue = if ($F.Value) {
                            '<ul>'
                            @($F.Value).ForEach( {
                                    "<li>$_</li>"
                                })
                            '</ul>'
                        }

                        @"
                        <tr>
                            <td id="$ProbType"></td>
                            <td colspan="7">
                                <p id="probTitle">$($F.Name)</p>
                                <p>$($F.Description)</p>
                                $ProbValue
                            </td>
                        </tr>
"@
                    }
                }
                #endregion

                #region HTML Mail overview Settings table $ Settings detail file
                $MailSettingsTable = $null

                if (
                    ($I.Settings) -and
                    ($I.File.Check.Type -notcontains 'FatalError') -and
                    ($I.Permissions.Check.Type -notcontains 'FatalError')
                ) {
                    $HtmlSettingsHeader = @'
                    <th id="matrixHeader" colspan="8">Settings</th>
                    <tr>
                        <td></td>
                        <td>ID</td>
                        <td>ComputerName</td>
                        <td>Path</td>
                        <td>Action</td>
                        <td>Duration</td>
                    </tr>
'@

                    $MailSettingsTable = $HtmlSettingsHeader

                    foreach ($S in $I.Settings) {
                        #region Get problem color
                        $ProbType = if ($S.Check.Type -contains 'FatalError') {
                            Get-HTNLidTagProbTypeHC -Name 'FatalError'
                        }
                        elseif ($S.Check.Type -contains 'Warning') {
                            Get-HTNLidTagProbTypeHC -Name 'Warning'
                        }
                        elseif ($S.Check.Type -contains 'Information') {
                            Get-HTNLidTagProbTypeHC -Name 'Information'
                        }
                        #endregion

                        #region HTML Settings Create tables
                        $SettingsDetailFatalError = foreach ($E in @($S.Check).Where( { $_.Type -eq 'FatalError' })) {
                            $htmlValue = ConvertTo-HtmlValueHC
                            @"
                            <tr>
                                <td id="probTypeError"></td>
                                <td colspan="7">
                                    <p id="probTitle">$($E.Name)</p>
                                    <p>$($E.Description)</p>
                                    $htmlValue
                                </td>
                            </tr>
"@
                        }

                        $SettingsDetailWarning = foreach ($E in @($S.Check).Where( { $_.Type -eq 'Warning' })) {
                            $htmlValue = ConvertTo-HtmlValueHC
                            @"
                            <tr>
                                <td id="probTypeWarning"></td>
                                <td colspan="7">
                                    <p id="probTitle">$($E.Name)</p>
                                    <p>$($E.Description)</p>
                                    $htmlValue
                                </td>
                            </tr>
"@
                        }

                        $SettingsDetailInfo = foreach ($E in @($S.Check).Where( { $_.Type -eq 'Information' })) {
                            $htmlValue = ConvertTo-HtmlValueHC
                            @"
                            <tr>
                                <td id="probTypeInfo"></td>
                                <td colspan="7">
                                    <p id="probTitle">$($E.Name)</p>
                                    <p>$($E.Description)</p>
                                    $htmlValue
                                </td>
                            </tr>
"@
                        }
                        #endregion

                        #region HTML Settings Create file
                        $SettingsDetail = @"
                            <!DOCTYPE html>
                            <html>
                            <head>
                                <style type="text/css">
                                    body {
                                        font-family: verdana;
                                        background-color: white;
                                    }

                                    h1 {
                                        background-color: black;
                                        color: white;
                                        margin-bottom: 10px;
                                        text-indent: 10px;
                                        page-break-before: always;
                                    }

                                    h2 {
                                        background-color: lightGrey;
                                        margin-bottom: 10px;
                                        text-indent: 10px;
                                        page-break-before: always;
                                    }

                                    h3 {
                                        background-color: lightGrey;
                                        margin-bottom: 10px;
                                        font-size: 16px;
                                        text-indent: 10px;
                                        page-break-before: always;
                                    }

                                    p {
                                        font-size: 14px;
                                        margin-left: 10px;
                                    }

                                    p.italic {
                                        font-style: italic;
                                        font-size: 12px;
                                    }

                                    table {
                                        font-size: 14px;
                                        border-collapse: collapse;
                                        border: 1px none;
                                        padding: 3px;
                                        text-align: left;
                                        padding-right: 10px;
                                        margin-left: 10px;
                                    }

                                    td,
                                    th {
                                        font-size: 14px;
                                        border-collapse: collapse;
                                        border: 1px none;
                                        padding: 3px;
                                        text-align: left;
                                        padding-right: 10px
                                    }

                                    li {
                                        font-size: 14px;
                                    }

                                    base {
                                        target="_blank"
                                    }
                                </style>
                            </head>

                            <body>
                                $htmlStyle
                                <table id="matrixTable">
                                <tr>
                                    <th id="matrixTitle" colspan="8"><a href="$($I.File.SaveFullName)">$($I.File.Item.Name)</a></th>
                                </tr>
                                $HtmlSettingsHeader
                                <tr>
                                    <td id="$ProbType"></td>
                                    <td>$($S.ID)</td>
                                    <td>$($S.Import.ComputerName)</td>
                                    <td>$($S.Import.Path)</td>
                                    <td>$($S.Import.Action)</td>
                                    <td>$(if($D = $S.JobTime.Duration){ '{0:00}:{1:00}:{2:00}' -f $D.Hours, $D.Minutes, $D.Seconds}else{'NA'})</td>
                                </tr>

                                $(if ($SettingsDetailFatalError) {'<th id="matrixHeader" colspan="8">Error</th>' + $SettingsDetailFatalError})
                                $(if ($SettingsDetailWarning) {'<th id="matrixHeader" colspan="8">Warning</th>' + $SettingsDetailWarning})
                                $(if ($SettingsDetailInfo) {'<th id="matrixHeader" colspan="8">Information</th>' + $SettingsDetailInfo})

                                </table>
                                <br>
                                $htmlLegend
                                    <h2>About</h2>
                                <table>
                                    <tr>
                                        <th>GroupName</th>
                                        <td>$($S.Import.GroupName)</td>
                                    </tr>
                                    <tr>
                                        <th>SiteCode</th>
                                        <td>$($S.Import.SiteCode)</td>
                                    </tr>
                                    <tr>
                                        <th>Start time</th>
                                        <td>$(
                                            if ($D = $S.JobTime.Start) {
                                                $D.ToString('dd/MM/yyyy HH:mm:ss (dddd)')
                                            }
                                            else {
                                                'NA'
                                            }
                                            )
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>End time</th>
                                        <td>$(
                                            if ($D = $S.JobTime.End) {
                                                $D.ToString('dd/MM/yyyy HH:mm:ss (dddd)')
                                            }
                                            else {
                                                'NA'
                                            }
                                            )
                                        </td>
                                    </tr>
                                </table>
                            </body>
                        </html>
"@

                        $SettingsFile = Join-Path -Path $I.File.LogFolder -ChildPath "ID $($S.ID) - Settings.html"
                        $SettingsDetail | Out-File -FilePath $SettingsFile -Encoding utf8
                        #endregion

                        $MailSettingsTable += @"
                        <tr>
                            <td id="$ProbType"></td>
                            <td><a href="$SettingsFile">$($S.ID)</a></td>
                            <td><a href="$SettingsFile">$($S.Import.ComputerName)</a></td>
                            <td><a href="$SettingsFile">$($S.Import.Path)</a></td>
                            <td><a href="$SettingsFile">$($S.Import.Action)</a></td>
                            <td><a href="$SettingsFile">$(if($D = $S.JobTime.Duration){ '{0:00}:{1:00}:{2:00}' -f $D.Hours, $D.Minutes, $D.Seconds}else{'NA'})</a></td>
                        </tr>
"@
                    }
                }
                #endregion

                @"
                <table id="matrixTable">
                    <tr>
                        <th id="matrixTitle" colspan="8"><a href="$($I.File.SaveFullName)">$($I.File.Item.Name)</a></th>
                    </tr>
                    <tr>
                        <th id="matrixFileInfo" colspan="8">Last change: $($I.File.ExcelInfo.LastModifiedBy) @ $($I.File.ExcelInfo.Modified.ToString('dd/MM/yyyy HH:mm:ss'))</th>
                    </tr>
                    $FileCheck
                    $FormDataCheck
                    $PermissionsCheck
                    $MailSettingsTable
                </table>
                <br><br>
"@
            }

            #region FatalError and warning count
            $count = @{
                FormData    = @{
                    Error   = @(
                        $importedMatrix.FormData.Check |
                        Where-Object Type -EQ 'FatalError'
                    ).count
                    Warning = @(
                        $importedMatrix.FormData.Check |
                        Where-Object Type -EQ 'Warning'
                    ).count
                }
                Permissions = @{
                    Error   = @(
                        $importedMatrix.Permissions.Check |
                        Where-Object Type -EQ 'FatalError'
                    ).count
                    Warning = @(
                        $importedMatrix.Permissions.Check |
                        Where-Object Type -EQ 'Warning'
                    ).count
                }
                Settings    = @{
                    Error   = @(
                        $importedMatrix.Settings.Check |
                        Where-Object Type -EQ 'FatalError'
                    ).count
                    Warning = @(
                        $importedMatrix.Settings.Check |
                        Where-Object Type -EQ 'Warning'
                    ).count
                }
                File        = @{
                    Error   = @(
                        $importedMatrix.File.Check |
                        Where-Object Type -EQ 'FatalError'
                    ).count
                    Warning = @(
                        $importedMatrix.File.Check |
                        Where-Object Type -EQ 'Warning'
                    ).count
                }
            }

            #endregion

            $htmlFormData = if ($CherwellFolder) {
                @"
            <p><b>Export to <a href="$CherwellFolder">Cherwell</a>:</b></p>
            <table id="overviewTable">
            <tr>
                <th>
                $(
                    if ($accessListSheet.count -and
                        $exportCsvAccessListParams.literalPath -and
                        (Test-Path -LiteralPath $exportCsvAccessListParams.literalPath)
                    ) {
@"
                        <a href="$($exportCsvAccessListParams.literalPath)">Access list</a>
"@
                    }
                    else {'Access list'}
                )
                </th>
                <td>$($accessListSheet.count)</td>
            </tr>
            <tr>
                <th>
                $(
                    if ($adObjectNamesSheet.count -and
                        $exportCsvAdParams.literalPath -and
                        (Test-Path -LiteralPath $exportCsvAdParams.literalPath)
                    ) {
@"
                        <a href="$($exportCsvAdParams.literalPath)">AD objects</a>
"@
                    }
                    else {'AD objects'}
                )
                </th>
                <td>$($adObjectNamesSheet.count)</td>
            </tr>
            <tr>
                <th>
                $(
                    if ($groupManagersSheet.count -and
                        $exportCsvGroupManagersParams.literalPath -and
                        (Test-Path -LiteralPath $exportCsvGroupManagersParams.literalPath)
                    ) {
@"
                        <a href="$($exportCsvGroupManagersParams.literalPath)">Group managers</a>
"@
                    }
                    else {'Group managers'}
                )
                </th>
                <td>$($groupManagersSheet.count)</td>
            </tr>
            <tr>
                <th>
            $(
                if ($formDataSheet.count -and
                    $exportCsvFormParams.literalPath -and
                    (Test-Path -LiteralPath $exportCsvFormParams.literalPath)
                ) {
@"
                    <a href="$($exportCsvFormParams.literalPath)">Form data</a>
"@
                }
                else {'From data'}
            )
                </th>
                <td>$($formDataSheet.count)</td>
            </tr>
            </table>
            $(
                if (
                    ($ExportParams.Path) -and
                    (Test-Path -LiteralPath $ExportParams.Path)
                ) {
@"
<p><i>* Check the <a href="$($ExportParams.Path)">overview</a> for details.</i></p>
"@
                }
            )
            <hr style="width:50%;text-align:left;margin-left:0">
"@
            }

            $errorCount = (
                $count.FormData.error + $count.Permissions.error +
                $count.Settings.error + $count.File.error
            )
            $warningCount = (
                $count.FormData.warning + $count.Permissions.warning +
                $count.Settings.warning + $count.File.warning
            )

            $htmlErrorWarningTable = if ($errorCount + $warningCount) {
                @"
            <p><b>Detected issues:</b></p>
            <table id="overviewTable">
            <tr>
                <td></td>
                <td>Errors</td>
                <td>Warnings</td>
            </tr>
            $(
                foreach ($item in ($count.GetEnumerator())) {
                    if ($item.Value.Error + $item.Value.warning) {
@"
                    <tr>
                        <th>$($item.Key)</th>
                        <td{0}>$($item.Value.Error)</td>
                        <td{1}>$($item.Value.Warning)</td>
                    </tr>
"@ -f $(if ($item.Value.Error) {' id="probTextError"'}),
$(if ($item.Value.Warning) {' id="probTextWarning"'})
                    }
                }
            )
            </table>
            <p><i>* Check the matrix results below for details.</i></p>
            <hr style="width:50%;text-align:left;margin-left:0">
"@
            }

            $htmlMail = @"
                $htmlStyle
                $htmlErrorWarningTable
                $htmlFormData
                <p><b>Matrix results per file:</b></p>
                $htmlMatrixTables
                $htmlLegend
"@

            $Subject = "$(@($importedMatrix).Count) matrix file{0}{1}{2}" -f $(
                if (@($importedMatrix).Count -ne 1) { 's' }
            ),
            $(
                if ($errorCount) {
                    ", $errorCount error{0}" -f $(
                        if ($errorCount -ne 1) { 's' }
                    )
                }
            ),
            $(
                if ($warningCount) {
                    ", $warningCount warning{0}" -f $(
                        if ($warningCount -ne 1) { 's' }
                    )
                }
            )

            $MailParams = @{
                To        = $MailTo
                Bcc       = $ScriptAdmin
                Priority  = if ($errorCount + $warningCount) { 'High' }
                else { 'Normal' }
                Subject   = $Subject
                Message   = $htmlMail
                Save      = "$matrixLogFile - Mail - $Subject.html"
                Header    = $ScriptName
                LogFolder = $LogFolder
            }
            Get-ScriptRuntimeHC -Stop
            Send-MailHC @MailParams
            #endregion

            #region Non terminating errors are reported to the admin
            # usually when Get-ADObjectDetailHC times out for groups too large
            if ($error) {
                $MailParams = @{
                    To        = $ScriptAdmin
                    Priority  = 'High'
                    Subject   = "FAILURE - $($error.count) non terminating errors"
                    Message   = "While running the permission matrix the following non terminating errors where reported: $($error.Exception.Message | Where-Object { $_  } | ConvertTo-HtmlListHC -Spacing Wide )"
                    Save      = "$matrixLogFile - Mail - $($error.count) non terminating errors.html"
                    Header    = $ScriptName
                    LogFolder = $LogFolder
                }
                Send-MailHC @MailParams
            }
            #endregion
        }
    }
    catch {
        Write-Warning $_
        Send-MailHC -To $ScriptAdmin -Subject FAILURE -Priority High -Message $_ -Header $ScriptName
        Write-EventLog @EventErrorParams -Message "FAILURE:`n`n- $_"; exit 1
    }
    finally {
        Get-Job | Remove-Job -Force -EA Ignore
        Remove-PSDrive ImportDir -EA Ignore
        Write-EventLog @EventEndParams
    }
}