#Requires -Version 7
#Requires -Modules ImportExcel, ServiceNow

<#
    .SYNOPSIS
        Synchronizes Permission Matrix form data with a specified ServiceNow 
        table.

    .DESCRIPTION
        This script connects to the ServiceNow API to populate the catalog 
        tables used by end-users to request access to specific folders. 
        
        It performs a "destructive sync": it first drops all existing records 
        in the target ServiceNow table, and then bulk-uploads the fresh records 
        generated by the Permission Matrix pipeline from the provided Excel 
        file.

        Security Feature: The JSON credentials file supports dynamically
        fetching secrets from the host's environment variables to avoid 
        hardcoding passwords. Simply prefix the JSON value with 'ENV:' 
        (e.g., "Password": "ENV:SNOW_SECURE_PASS").

    .PARAMETER CredentialsFilePath
        The absolute path to the .JSON file containing the ServiceNow logon 
        credentials.

    .PARAMETER Environment
        The specific ServiceNow environment/node to target (e.g., 'Test', 
        'Prod'). This key must exist inside the Credentials JSON file.

    .PARAMETER FormDataExcelFilePath
        The absolute path to the compiled Excel file containing the structured 
        records to be uploaded.

    .PARAMETER ExcelFileWorksheetName
        The specific worksheet inside the FormDataExcelFilePath to read the 
        records from (usually 'FormData').

    .PARAMETER TableName
        The exact physical name of the target table in ServiceNow
        (e.g., 'u_permission_matrix_roles').

    .PARAMETER MaxRetries
        The maximum number of retry attempts for network/API timeouts when 
        deleting or creating records. (Default: 3, minimum 1)

    .PARAMETER ChunkSize
        The number of existing records to fetch and delete per batch when 
        clearing the target table. The table is drained in batches of this size 
        rather than pulled in full, which keeps memory flat and limits the 
        impact of a transient network failure to a single batch. (Default: 200)

    .EXAMPLE
        .\Update-ServiceNow.ps1 `
            -CredentialsFilePath 'C:\Secrets\ServiceNow.json' `
            -Environment 'Prod' `
            -FormDataExcelFilePath 'C:\Matrix\Exports\FormData.xlsx' `
            -ExcelFileWorksheetName 'FormData' `
            -TableName 'u_custom_matrix_roles' `
            -MaxRetries 5
#>

param (
    [Parameter(Mandatory)]
    [String]$CredentialsFilePath,
    [Parameter(Mandatory)]
    [String]$Environment,
    [Parameter(Mandatory)]
    [String]$FormDataExcelFilePath,
    [Parameter(Mandatory)]
    [String]$ExcelFileWorksheetName,
    [Parameter(Mandatory)]
    [String]$TableName,
    [ValidateRange(1, [int]::MaxValue)]
    [int]$MaxRetries = 3,
    [ValidateRange(1, 10000)]
    [int]$ChunkSize = 200
)

begin {
    function Get-StringValueHC {
        <#
        .SYNOPSIS
            Retrieve a string from the environment variables or a regular
            string.

        .DESCRIPTION
            This function checks the 'Name' property. If the value starts with
            'ENV:', it attempts to retrieve the string value from the specified
            environment variable. Otherwise, it returns the value directly.

        .PARAMETER Name
            Either a string starting with 'ENV:'; a plain text string or NULL.

        .EXAMPLE
            Get-StringValueHC -Name 'ENV:passwordVariable'

            # Output: the environment variable value of $ENV:passwordVariable
            # or an error when the variable does not exist

        .EXAMPLE
            Get-StringValueHC -Name 'mySecretPassword'

            # Output: mySecretPassword

        .EXAMPLE
            Get-StringValueHC -Name ''

            # Output: NULL
        #>
        param (
            [String]$Name
        )

        if (-not $Name) {
            return $null
        }
        elseif (
            $Name.StartsWith('ENV:', [System.StringComparison]::OrdinalIgnoreCase)
        ) {
            $envVariableName = $Name.Substring(4).Trim()
            $envStringValue = Get-Item -Path "Env:\$envVariableName" -EA Ignore
            if ($envStringValue) {
                return $envStringValue.Value
            }
            else {
                throw "Environment variable '$envVariableName' not found."
            }
        }
        else {
            return $Name
        }
    }
    function New-ServiceNowSessionHC {
        [CmdletBinding()]
        param (
            [parameter(Mandatory)]
            [String]$Uri,
            [parameter(Mandatory)]
            [String]$UserName,
            [parameter(Mandatory)]
            [String]$Password,
            [parameter(Mandatory)]
            [String]$ClientId,
            [parameter(Mandatory)]
            [String]$ClientSecret
        )
        try {
            $userCred = New-Object System.Management.Automation.PSCredential(
                $UserName,
                ($Password | ConvertTo-SecureString -AsPlainText -Force)
            )

            $clientCred = New-Object System.Management.Automation.PSCredential(
                $ClientId,
                ($ClientSecret | ConvertTo-SecureString -AsPlainText -Force)
            )

            Write-Verbose "Create new ServiceNow session to '$Uri'"

            $params = @{
                Url              = $Uri
                Credential       = $userCred
                ClientCredential = $clientCred
            }
            New-ServiceNowSession @params
        }
        catch {
            $errorMessage = $_; $Error.RemoveAt(0)
            throw "Failed to create a ServiceNow session with Uri '$Uri' UserName '$UserName' ClientId '$ClientId': $errorMessage"
        }
    }

    $ErrorActionPreference = 'Stop'

    try {
        #region Import .JSON file
        Write-Verbose "Import .json file '$CredentialsFilePath'"

        $serviceNowJsonFileContent = Get-Content $CredentialsFilePath -Raw -Encoding UTF8 | ConvertFrom-Json
        #endregion

        #region Test .JSON file properties
        Write-Verbose 'Test .json file properties'

        $serviceNowEnvironment = $serviceNowJsonFileContent.($Environment)

        if (-not $serviceNowEnvironment) {
            throw "Failed to find environment '$($Environment)' in the ServiceNow environment file '$($CredentialsFilePath)'"
        }

        @(
            'Uri', 'UserName', 'Password', 'ClientId', 'ClientSecret'
        ).where(
            { -not $serviceNowEnvironment.$_ }
        ).foreach(
            {
                throw "Property '$_' not found for environment '$($Environment)' in file '$($CredentialsFilePath)'"
            }
        )
        #endregion
    }
    catch {
        throw "ServiceNow credentials file '$CredentialsFilePath': $_"
    }
}

process {
    #region Import records to upload
    try {
        Write-Verbose 'Import records to upload from .XLSX file'

        $params = @{
            Path          = $FormDataExcelFilePath
            WorksheetName = $ExcelFileWorksheetName
        }
        $recordsToUpload = Import-Excel @params
    }
    catch {
        # FIX: corrected the malformed/garbled message (missing closing quote
        # and a stray double space) so the path and worksheet read cleanly.
        throw "Failed to import records to upload from file '$FormDataExcelFilePath' with worksheet name '$ExcelFileWorksheetName': $_"
    }
    #endregion

    if ($recordsToUpload) {
        #region Create global variable $ServiceNowSession
        $params = @{
            Uri          = Get-StringValueHC -Name $serviceNowEnvironment.Uri
            UserName     = Get-StringValueHC -Name $serviceNowEnvironment.UserName
            Password     = Get-StringValueHC -Name $serviceNowEnvironment.Password
            ClientId     = Get-StringValueHC -Name $serviceNowEnvironment.ClientId
            ClientSecret = Get-StringValueHC -Name $serviceNowEnvironment.ClientSecret
        }
        New-ServiceNowSessionHC @params
        #endregion

        #region Remove all records in the ServiceNow table (chunked)
        # The table is cleared in small chunks rather than pulled in full: this
        # keeps memory flat and limits the blast radius of a network blip to a
        # single chunk (each chunk is a fresh request with its own retries).
        #
        # We fetch and delete in a drain pattern: always request the current
        # *top* $ChunkSize records and delete them. Because the delete shrinks
        # the table, we deliberately do NOT use an increasing -Skip offset -
        # offsetting after a delete would step over rows that have shifted up.
        #
        # $failedSysIds guards against an infinite loop: a record that can never
        # be removed keeps reappearing at the top of the table, so we track such
        # records and stop once a whole chunk consists only of them (no progress
        # possible). Removal stays non-fatal - the upload proceeds regardless.
        Write-Verbose "Remove all records in ServiceNow table '$TableName' in chunks of $ChunkSize"

        $removeParams = @{
            Confirm = $false
            Verbose = $false
        }

        $removedCount = 0
        $chunkNumber = 0
        $failedSysIds = [System.Collections.Generic.HashSet[string]]::new()

        while ($true) {
            $chunkNumber++

            try {
                $chunk = @(Get-ServiceNowRecord -Table $TableName -First $ChunkSize)
            }
            catch {
                throw "Failed to retrieve records (chunk $chunkNumber) from ServiceNow table '$TableName': $_"
            }

            if ($chunk.Count -eq 0) {
                break
            }

            # Drop records we've already given up on; if that empties the chunk,
            # the same un-removable records are cycling back and we must stop.
            $pending = @(
                $chunk | Where-Object {
                    -not $failedSysIds.Contains([string]$_.sys_id)
                }
            )

            if ($pending.Count -eq 0) {
                Write-Warning "Stopping removal of '$TableName': a chunk of $($chunk.Count) record(s) could not be removed on earlier attempts. $($failedSysIds.Count) record(s) remain and may surface as duplicates after upload."
                break
            }

            Write-Verbose "Chunk $chunkNumber : removing $($pending.Count) record(s) ($removedCount removed so far)"

            foreach ($tableRecord in $pending) {
                $attempt = 0
                $removed = $false

                while ($attempt -lt $MaxRetries) {
                    $attempt++

                    try {
                        Write-Verbose "Remove record '$($tableRecord.sys_id)'$(if($attempt -gt 1) {' - Retry'})"

                        $tableRecord | Remove-ServiceNowRecord @removeParams

                        $removed = $true
                        break
                    }
                    catch {
                        # Sleep only *between* attempts, never after the last one.
                        if ($attempt -ge $MaxRetries) {
                            [void]$failedSysIds.Add([string]$tableRecord.sys_id)

                            Write-Warning "Failed to remove record '$($tableRecord.sys_id)' after $MaxRetries attempts; continuing. Last error: $_"
                        }
                        else {
                            Write-Warning "Attempt $attempt of $MaxRetries failed to remove record '$($tableRecord.sys_id)'. Retrying in 3 seconds... Error: $_"

                            Start-Sleep -Seconds 3
                        }
                    }
                }

                if ($removed) {
                    $removedCount++
                }
            }

            # A short chunk means fewer than a full page were left, so the table
            # is now drained. A full chunk may have more behind it - loop again.
            if ($chunk.Count -lt $ChunkSize) {
                break
            }
        }

        Write-Verbose "Removed $removedCount record(s) from '$TableName'"
        #endregion

        #region Create new records in the ServiceNow table
        Write-Verbose "Create $($recordsToUpload.Count) records in the ServiceNow table '$TableName'"

        $currentRecordCount = 0
        $totalRecordCount = $recordsToUpload.Count

        $createParams = @{
            Table   = $TableName
            Verbose = $false
        }

        $recordsToUploadHashTable = $recordsToUpload |
        ConvertTo-Json | ConvertFrom-Json -AsHashtable

        foreach ($record in $recordsToUploadHashTable) {
            $attempt = 0
            $currentRecordCount++

            while ($attempt -lt $MaxRetries) {
                $attempt++

                try {
                    Write-Verbose "($currentRecordCount/$totalRecordCount) Create record for matrix '$($record.u_matrixfilename)' AD object '$($record.u_adobjectname)' $(if($attempt -gt 1) {' - Retry'})"

                    $record | New-ServiceNowRecord @createParams

                    break
                }
                catch {
                    if ($attempt -ge $MaxRetries) {
                        throw "CRITICAL FAILURE: Could not create record for matrix '$($record.u_matrixfilename)' AD object '$($record.u_adobjectname)' after $MaxRetries attempts. Last error: $_"
                    }

                    Write-Warning "Attempt $attempt of $MaxRetries failed for matrix '$($record.u_matrixfilename)' AD object '$($record.u_adobjectname)'. Retrying in 3 seconds... Error: $_"

                    Start-Sleep -Seconds 3
                }
            }
        }
        #endregion
    }
}